# Generated by Django 4.0.6 on 2022-07-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=250)),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
    ]
