# Generated by Django 4.0.6 on 2022-08-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('Electrical', 'Electrical'), ('Mechanical', 'Mechanical')], max_length=10)),
                ('description', models.TextField(max_length=250)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created'],
            },
        ),
    ]
