# Generated by Django 4.0.6 on 2022-07-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notifications_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-created'], 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
    ]
